server {
    listen 80;
    server_name _;
    root /var/www/html;
    index public.php;
    client_max_body_size 10m;

    location / {
        try_files $uri $uri/ /public.php?$query_string;
    }
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass absensi-fpm:9000;
    }
    location ~ \.(js|css|png|jpg|jpeg|gif|svg|woff|woff2)$ {
        expires 30d;
        access_log off;
    }
}
